// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMBKkUoFYDXnV9NAGAxnEY7LfuoPxgRyw',
    appId: '1:444354708357:web:34c70072079a8abecdbaec',
    messagingSenderId: '444354708357',
    projectId: 'ulearning-d0b94',
    authDomain: 'ulearning-d0b94.firebaseapp.com',
    storageBucket: 'ulearning-d0b94.appspot.com',
    measurementId: 'G-DEHXQTSQSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvK8a4ialIoKQ6J4v_LhOA_RicXPnZKJg',
    appId: '1:444354708357:android:71bceb095975fc4fcdbaec',
    messagingSenderId: '444354708357',
    projectId: 'ulearning-d0b94',
    storageBucket: 'ulearning-d0b94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFG5yspDpzbHzCbBTAnugKCX57A2L6TII',
    appId: '1:444354708357:ios:69047fc5b47f0c77cdbaec',
    messagingSenderId: '444354708357',
    projectId: 'ulearning-d0b94',
    storageBucket: 'ulearning-d0b94.appspot.com',
    androidClientId: '444354708357-lsv51vi3lto4aqjp1hmqu74hhrj4qn6m.apps.googleusercontent.com',
    iosClientId: '444354708357-775h8osgb138t5iehe97mctqjf4akmtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursesApp',
  );
}
